# https://travis-ci.org/Llamatech/review-me

language: node_js
sudo: true

node_js:
  - "iojs"
  - "node"
  - "7"
env:
  global:
    - MONGO_URL=mongodb://127.0.0.1:27017
    - ROOT_URL=http://review-me.margffoy-tuay.com

addons:
  hosts:
    - review-me.margffoy-tuay.com

before_install:
  - "meteor || curl https://install.meteor.com | /bin/sh"

services:
  - mongodb

install:
  - meteor --version
  - echo $METEOR_SETTINGS > settings-development.json
  - ./node_modules/.bin/eslint .

script:
  - echo Hi!